// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocnhxoaqwkisihoyjlbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jbmh4b2Fxd2tpc2lob3lqbGJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjk4MDQsImV4cCI6MjA2ODYwNTgwNH0.z9SGrUURulqH7mTjLALnQ8zapRhiF4BzdefcqMdBcVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});